name: VentureLibs
version: '1.0'
main: net.blockventuremc.VentureLibs
description: Plugin
api-version: '1.20'

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true

    TAB:
      load: BEFORE
      required: true