name: Dokka Documentation with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate API documentation
        env:
          PACKAGE_USER: ${{ secrets.PACKAGE_USER }}
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
        run: ./gradlew dokkaHtml

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/dokka/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1